version: 3.7
services:
  jwt-security:
    --hostname: security.com
    build:
      context: .
    image: security:1.1
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 2
      depends_on: mongo

  mongo:
    image: mongo
    ports:
      - target: 27017
        published: 27017
        protocol: tcp
    networks:
      - overlay
    deploy:
      mode: replicated
      replicas: 2
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
